import useROIStore from "@/features/maps/stores/use-roi-store";
import useQueryOutputReadyFromVectorLayer from "@/features/maps/stores/map-queries-stores/useQueryOutputReadyFromVectorLayerStore";
import useQueryRasterFromVectorLayerStore from "@/features/maps/stores/map-queries-stores/useQueryRasterFromVectorLayerStore";
import useQueryStore from "@/features/maps/stores/map-queries-stores/useQueryReadyStore";
import useChartRequestedTypeStore from "@/features/maps/stores/plots-stores/useChartRequestedTypeStore";
import usePlotReadyDataStore from "@/features/maps/stores/plots-stores/usePlotReadyDataStore";
import usePlotReadyDataFromVectorLayerStore from "@/features/maps/stores/plots-stores/usePlotReadyFromVectorLayerStore";
import { useAgolLayersStore } from "@/features/maps/stores/use-agol-layers-store";
import useColorPickerStore from "@/features/maps/stores/use-color-picker-store";
import useCursorStore from "@/features/maps/stores/use-cursor-store";
import useDrawnFeatureOnMapStore from "@/features/maps/stores/use-drawn-feature-on-map-store";
import useFunctionStore from "@/features/maps/stores/use-function-store";
import { useGeeOutputStore } from "@/features/maps/stores/use-gee-ouput-store";
import useGeojsonStore from "@/features/maps/stores/use-geojson-store";
import useLayerSelectionStore from "@/features/maps/stores/use-layer-selection-store";
import useMapDisplayStore from "@/features/maps/stores/use-map-display-store";
import useMapLayersStore from "@/features/maps/stores/use-map-layer-store";
import useZoomRequestStore from "@/features/maps/stores/use-map-zoom-request-store";
import useMapLegendStore from "@/features/maps/stores/use-map-legend-store";
import useTableStore from "@/features/maps/stores/use-table-store";
import { useAttachmentStore } from "@/features/chat/stores/use-attachments-store";
import useChatSourcesStore from "@/features/chat/stores/use-chat-response-sources-store";
import useDraftedReportStore from "@/features/chat/stores/use-drafted-report-store";
import { useButtonsStore } from "@/stores/use-buttons-store";

export function resetChatStores() {
  useROIStore.getState().reset();
  useQueryOutputReadyFromVectorLayer.getState().reset();
  useQueryRasterFromVectorLayerStore.getState().reset();
  useQueryStore.getState().reset();
  useChartRequestedTypeStore.getState().reset();
  usePlotReadyDataStore.getState().reset();
  usePlotReadyDataFromVectorLayerStore.getState().reset();
  useButtonsStore.getState().reset();
  useColorPickerStore.getState().reset();
  useCursorStore.getState().reset();
  useDrawnFeatureOnMapStore.getState().reset();
  useFunctionStore.getState().reset();
  useGeeOutputStore.getState().reset();
  useGeojsonStore.getState().reset();
  useLayerSelectionStore.getState().reset();
  useMapDisplayStore.getState().reset();
  useMapLayersStore.getState().reset();
  useZoomRequestStore.getState().reset();
  useMapLegendStore.getState().reset();
  useTableStore.getState().reset();
  useAttachmentStore.getState().reset();
  useChatSourcesStore.getState().reset();
  useDraftedReportStore.getState().reset();
}
